In [6]:
import pandas as pd
import numpy as np
from statistics import mean
import math

pd.set_option('display.max_columns', 30)

types = {'id': int, 'provincia': str}

training_data = pd.read_csv(r'../../data/TP2/train.csv', dtype = types, usecols=['id','provincia','tipodepropiedad' ,'direccion'])
evaluation_data = pd.read_csv('../../data/TP2/test.csv', dtype = types, usecols=['id','provincia','tipodepropiedad', 'direccion'])

training_data.head()

,id,tipodepropiedad,direccion,provincia
0,254099,Apartamento,Avenida Division del Norte 2005,Distrito Federal
1,53461,Casa en condominio,AV. MEXICO,Distrito Federal
2,247984,Casa,Urbi Tonala,Jalisco
3,209067,Casa,IGNACIO MANUEL ALTAMIRANO 128,Edo. de México
4,185997,Apartamento,PASEOS DEL SOL,Jalisco

In [4]:
training_data["direccion"] = training_data["direccion"].apply(lambda x: str(x).lower())
evaluation_data["direccion"] = evaluation_data["direccion"].apply(lambda x: str(x).lower())
training_data["tipodepropiedad"] = training_data["tipodepropiedad"].apply(lambda x: str(x).lower())
evaluation_data["tipodepropiedad"] = evaluation_data["tipodepropiedad"].apply(lambda x: str(x).lower())

In [27]:
training_data['sum'] = 1
unique = training_data.groupby(['provincia','direccion','tipodepropiedad']).agg(unique_dirs = ('sum','sum')).reset_index()
unique['sum'] = 1
unique = unique.groupby(['provincia']).agg(unique_dirs = ('sum','sum'), total_dirs =('unique_dirs','sum') ).reset_index()
unique['porcentaje_dir_unicas_provincia'] = unique['unique_dirs']/unique['total_dirs']
unique['log_dir_unicas_provincia'] = unique['unique_dirs'].apply(math.log)
unique = unique.drop(['unique_dirs','total_dirs'],axis=1)
td = training_data.merge(unique, on='provincia')
td.head()

,id,tipodepropiedad,direccion,provincia,sum,porcentaje_dir_unicas_provincia,log_dir_unicas_provincia
0,254099,Apartamento,Avenida Division del Norte 2005,Distrito Federal,1,0.808692,10.653771
1,53461,Casa en condominio,AV. MEXICO,Distrito Federal,1,0.808692,10.653771
2,126147,Apartamento,Condominio Tlalpan 2B,Distrito Federal,1,0.808692,10.653771
3,130216,Casa,"MATIAS ROMERO, COLONIA DEL VALLE",Distrito Federal,1,0.808692,10.653771
4,73348,Apartamento,Pazaje Santa Cruz,Distrito Federal,1,0.808692,10.653771

In [23]:
evaluation_data['sum'] = 1
unique = evaluation_data.groupby(['provincia','direccion','tipodepropiedad']).agg(unique_dirs = ('sum','sum')).reset_index()
unique['sum'] = 1
unique = unique.groupby(['provincia']).agg(unique_dirs = ('sum','sum'), total_dirs =('unique_dirs','sum') ).reset_index()
unique['porcentaje_dir_unicas_provincia'] = unique['unique_dirs']/unique['total_dirs']
unique['log_dir_unicas_provincia'] = unique['unique_dirs'].apply(math.log)
unique = unique.drop(['unique_dirs','total_dirs'],axis=1)
ed = evaluation_data.merge(unique, on='provincia')
ed.head()

,id,tipodepropiedad,direccion,provincia,sum,porcentaje_dir_unicas_provincia,log_dir_unicas_provincia
0,4941,Casa,Bosque de Cedros,Distrito Federal,1,0.911966,9.392329
1,115253,Apartamento,"Pueblo de los Reyes, Coyoacán, Mexico D.F.",Distrito Federal,1,0.911966,9.392329
2,195272,Casa,NORTE 0,Distrito Federal,1,0.911966,9.392329
3,238663,Apartamento,"Calle Tepetlapa, Andador 6",Distrito Federal,1,0.911966,9.392329
4,253578,Apartamento,cda. nicolas san juan,Distrito Federal,1,0.911966,9.392329

In [28]:
td = td.drop(['tipodepropiedad','direccion','provincia','sum'],axis = 1)
ed = ed.drop(['tipodepropiedad','direccion','provincia','sum'], axis = 1)
td.head()

       id  porcentaje_dir_unicas_provincia  log_dir_unicas_provincia
0  254099                         0.808692                 10.653771
1   53461                         0.808692                 10.653771
2  126147                         0.808692                 10.653771
3  130216                         0.808692                 10.653771
4   73348                         0.808692                 10.653771

In [26]:
td.drop(['log_dir_unicas_provincia'],axis = 1).to_csv('../../res/ftr/porcentaje_dirs_uniq.csv')
ed.drop(['log_dir_unicas_provincia'],axis = 1).to_csv('../../res/ftr/porcentaje_dirs_uniq_evaluation.csv')


td.drop(['porcentaje_dir_unicas_provincia'],axis = 1).to_csv('../../res/ftr/log_dirs_uniq.csv')
ed.drop(['porcentaje_dir_unicas_provincia'],axis = 1).to_csv('../../res/ftr/log_dirs_uniq_evaluation.csv')