In [1]:
import pandas as pd
import numpy as np
from statistics import mean

pd.set_option('display.max_columns', 30)

types = {'id': int, 'provincia': str}

training_data = pd.read_csv('../../data/TP2/train.csv', dtype = types, usecols=['id', 'provincia'])
evaluation_data = pd.read_csv('../../data/TP2/test.csv', dtype = types, usecols=['id', 'provincia'])

training_data.head()

       id         provincia
0  254099  Distrito Federal
1   53461  Distrito Federal
2  247984           Jalisco
3  209067    Edo. de México
4  185997           Jalisco

In [2]:
Sinaloa = [53, 58, 76, 85, 47, 44]
Chihuahua = [58, 58, 88, 111, 74, 42]
Morelos = [31, 51, 33, 33, 19, 8]
Guerrero = [71, 45, 42, 48, 46, 30]
Colima = [113, 42, 27, 15, 9, 6]
Durango = [11, 40, 27, 66, 60, 28]
Nuevo_Leon = [12, 32, 44, 18, 6, 6]
Tamaulipas = [32, 31, 26, 22, 9, 10]
Coahuila = [9, 29, 25, 15, 9, 7]
Guanajuato = [38, 25, 19, 9, 8, 5]
Nayarit = [36, 25, 47, 38, 15]
Sonora = [25, 20, 18, 26, 20, 16]
Michoacan = [36, 19, 20, 18, 18, 14]
Quintana_Roo = [27, 18, 19, 17, 13, 15]
Baja_California = [60, 18, 20, 27, 24, 28]
Jalisco = [20, 17, 17, 12, 8, 7]
San_Luis_Potosi = [18, 15, 15, 12, 6, 9]
Zacatecas = [43, 14, 9, 8, 6, 5]
Oaxaca = [21, 13, 12, 14, 21, 21]
Chiapas = [11, 12, 13, 11, 10, 8]
Puebla = [17, 11, 11, 7, 7, 8]
Distrito_Federal = [15, 9, 9, 9, 8, 8]
Veracruz = [19, 9, 7, 5, 5, 7]
Edo_de_Mexico = [18, 8, 10, 8, 9, 9]
Campeche = [9, 8, 7, 7, 5, 6]
Queretaro = [11, 6, 6, 3, 5, 3]
Tabasco = [18, 6, 8, 7, 6, 7]
Baja_California_Sur = [91, 6, 6, 8, 5, 5]
Tlaxcala = [9, 5, 6, 4, 4, 4]
Aguascalientes = [6, 4, 19, 6, 6, 6]
Hidalgo = [11, 3, 5, 6, 6, 6]
Yucatan = [2, 2, 2, 2, 2, 2]

murder_rate_by_entity = {
    'Distrito Federal': mean(Distrito_Federal),
    'Jalisco': mean(Jalisco),
    'Edo. de México': mean(Edo_de_Mexico),
    'Oaxaca': mean(Oaxaca),
    'Quintana Roo': mean(Quintana_Roo),
    'Colima': mean(Colima),
    'San luis Potosí': mean(San_Luis_Potosi),
    'Nuevo León': mean(Nuevo_Leon),
    'Querétaro': mean(Queretaro),
    'Tamaulipas': mean(Tamaulipas),
    'Puebla': mean(Puebla),
    'Yucatán': mean(Yucatan),
    'Morelos': mean(Morelos),
    'Guerrero': mean(Guerrero),
    'Tabasco': mean(Tabasco),
    'Guanajuato': mean(Guanajuato),
    'Hidalgo': mean(Hidalgo),
    'Veracruz': mean(Veracruz),
    'Chihuahua': mean(Chihuahua),
    'Aguascalientes': mean(Aguascalientes),
    'Sonora': mean(Sonora),
    'Michoacán': mean(Michoacan),
    'Baja California Norte': mean(Baja_California),
    'Baja California Sur': mean(Baja_California_Sur),
    'Coahuila': mean(Coahuila),
    'Durango': mean(Durango),
    'Sinaloa': mean(Sinaloa),
    'Chiapas': mean(Chiapas),
    'Nayarit': mean(Nayarit),
    'Tlaxcala': mean(Tlaxcala),
    'Campeche': mean(Campeche),
    'Zacatecas': mean(Zacatecas),
    'nan' : None
}

In [3]:
training_data['provincia'] = training_data['provincia'].apply(lambda x: str(x))
evaluation_data['provincia'] = evaluation_data['provincia'].apply(lambda x: str(x))

training_data['murder_rate_of_entity'] = training_data['provincia'].apply(lambda x: murder_rate_by_entity[x])
evaluation_data['murder_rate_of_entity'] = evaluation_data['provincia'].apply(lambda x: murder_rate_by_entity[x])

training_data.drop(columns=['provincia'],inplace=True)
evaluation_data.drop(columns=['provincia'],inplace=True)

training_data.head()

       id  murder_rate_of_entity
0  254099               9.666667
1   53461               9.666667
2  247984              13.500000
3  209067              10.333333
4  185997              13.500000

In [4]:
training_data.to_csv('../../res/ftr/murder_rate_of_entity_train.csv')
evaluation_data.to_csv('../../res/ftr/murder_rate_of_entity_evaluation.csv')